[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common" }
slint = "1.14.1"
tokio = { version = "1.48.0", features = ["full"] }

[build-dependencies]
slint-build = "1.14.1"
